name: Continuous Integration
on: [push]
jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    environment: testing
    steps:
      - uses: actions/checkout@v2
      - run: brew install portmidi
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          LIBRARY_PATH: /opt/homebrew/Cellar/portmidi/2.0.4_1/lib
        with:
          command: test
