name: Continuous Integration
on: [push]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y libportmidi-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        with:
          command: test
